#!/usr/bin/env python3
"""
Quick launcher for Neural Core - just run: ./neural
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from neural_core import main

if __name__ == '__main__':
    main()